//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp17.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriteImages
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ImageUrl { get; set; }

        public string Title { get; set; }
    }
}
